[packages]
    [packages.darwin]
    brews = []
    casks = []

    [packages.linux]
    flatpaks = ["flatseal"]

        [packages.linux.fedora]
            package_manager = "dnf"
            exclude_flag = "--exclude="

            [packages.linux.fedora.cli]
                common = ["fish", "git", "neovim", "btop", "bat", "zoxide", "ripgrep", "fzf", "fd-find", "-nodejs"]

            [packages.linux.fedora.external]
                common = []
